### ISSUE TITLE
Several things broken with Rabby wallet

### ISSUE THREAD

**Issue by ches** [solidlyexchange/solidly.exchange#26]
I've been happy with DeBank's [Rabby wallet](https://rabby.io/) lately as an alternative to Metamask, I find the UX preferable and even some functional things, like it seems to do better at gas estimation on Fantom.

Anyway, Solidly has been unusable for me with Rabby, and it's the only dApp that I've ever had any such problem with whatsoever—it has served as drop-in Metamask-compatible on numerous other protocols I use.

I understand it's a lot to ask to test for numerous wallets, but it appears Solidly frontend may have some coupling to Metamask specifics, and if those can be smoothed out without degrading functionality or experience then it might improve compatibility for other alternative wallets, perhaps for mobile as well.

I will come back and add specific error details to this issue the next time I need to make a problematic type of transaction, just wanted to start an umbrella issue—if anyone else using Rabby can reproduce before I do, they can add JS errors etc. in comments here. Just try to do almost anything useful on Solidly—swap, add liquidity—and I think you'll encounter problems.

Some though not all issues stemmed from error handling when RPCs were overloaded / fronting proxy returning 503s, so those might take more effort to reproduce, fault injecting on a test RPC instance.

**Comment by vvvvvv1vvvvvv** [comment]
fixed in v0.23.0 in Rabby side, just update to the latest version then everything works fine

**Comment by antonnell** [comment]
@ches All gucci or your side or should I investigate more?

**Comment by ches** [comment]
Thank you for patching the extension @vvvvvv1vvvvvv and for pointing out the update.

I confirmed my extension updated to v0.23.0 and restarted my browser for good measure, force-refreshed / cleared site data / used an incognito window but I'm still seeing these when attempting to swap, add liquidity, or vote on gauges:

<img width="633" alt="JavaScript error in modal on Solidly web UI" src="https://user-images.githubusercontent.com/13277/156184869-fa404635-5be6-48db-b934-9e605d947605.png">

If these are Rabby issues though and nothing to do with Solidly using out-of-spec APIs or anything like that, I can move this issue to the Rabby tracker.
